name: Metrics
on:
  # Agenda a atualização para rodar a cada 12 horas
  # schedule: [{cron: "0 */12 * * *"}]

  # Agenda a atualização para rodar toda segunda-feira (às 00:00 UTC)
  schedule: [{cron: "0 0 * * 1"}]
  # Permite que você execute manualmente pela aba Actions se quiser testar
  workflow_dispatch:
  # Atualiza sempre que você fizer um push na branch principal
  # push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Cache de Métricas
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.FerrerasRP.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Opções de exibição (Configure como preferir)
          user: FerrerasRP
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugins adicionais opcionais (Exemplos):
          plugin_languages_indepth: no
          plugin_lines: yes               # Mostra linhas de código modificadas
          plugin_languages: yes           # Mostra idiomas mais utilizados
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-size percentage
          plugin_achievements: no         # Mostra conquistas do GitHub em formato de medalhas
