name: GitHub Readme Stats Action

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  workflow_dispatch:     # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gera o card principal de estatísticas
      - name: Generate Stats Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=FerrerasRP&show_icons=true&theme=default
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Gera o card de linguagens mais usadas
      - name: Generate Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=FerrerasRP&layout=compact&theme=default
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update generated github stats cards"
          file_pattern: "*.svg"