name: GitHub Readme Stats Action

on:
  schedule:
    - cron: "0 0 * * *" # Executa todo dia à meia-noite
  workflow_dispatch:     # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gera o card de linguagens mais usadas pt-BR
      - name: Generate Top Languages Card pt-BR
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=FerrerasRP&layout=compact&theme=default&locale=pt
          path: top-langs-pt-br.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # Gera o card de linguagens mais usadas en-US
      - name: Generate Top Languages Card en-US
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=FerrerasRP&layout=compact&theme=default&locale=en
          path: top-langs-en-us.svg
          token: ${{ secrets.GITHUB_TOKEN }}

       # Gera o card de linguagens mais usadas es-ES
      - name: Generate Top Languages Card es-ES
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=FerrerasRP&layout=compact&theme=default&locale=es
          path: top-langs-es-es.svg
          token: ${{ secrets.GITHUB_TOKEN }}
        
      # Gera o card das metricas do perfil
      - name: Generate Metric Card
        uses: lowlighter/metrics@latest
        with:
            filename: metrics.svg
            token: ${{ secrets.GITHUB_TOKEN }}
            user: FerrerasRP
            template: classic
            base: header, activity, community, repositories, metadata
            plugins_languages: yes
            plugins_languages_details: bytes-size, percentage
            plugins_languages_ignored: ""
            config_timezone: America/Sao_Paulo
    
      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update generated github stats cards"
          file_pattern: "*.svg"
